DROP TABLE IF EXISTS MOVIES;

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('TO KEFALAIO', '1867-09-25', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('KRATOS KAI EPANASTASH', '1917-09-25', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('AREIANARA', '1914-09-25', 'EXADAKTYLOS', '2019-09-25');



DROP TABLE IF EXISTS MOVIE_DETAILS;

INSERT INTO Details (DIRECTOR, DESC, USERINSERT, TIMEINSERT, MOVIE_ID) VALUES
('MARX', 'Very Good', 'EXADAKTYLOS', '2019-09-25', 1);

INSERT INTO Details (DIRECTOR, DESC, USERINSERT, TIMEINSERT, MOVIE_ID) VALUES
('LENIN', 'Very Good', 'EXADAKTYLOS', '2019-09-25', 2);

INSERT INTO Details (DIRECTOR, DESC, USERINSERT, TIMEINSERT, MOVIE_ID) VALUES
('PATSIMAS', 'Very Good', 'EXADAKTYLOS', '2019-09-25', 3);




