DROP TABLE IF EXISTS MOVIES;

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
      ('TO KEFALAIO', '1867-09-25', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('KRATOS KAI EPANASTASH', '1917-09-25', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('AREIANARA', '1914-09-25', 'EXADAKTYLOS', '2019-09-25');



DROP TABLE IF EXISTS MOVIES_DETAILS;

INSERT INTO MovieDetails (DIRECTOR, DESC, USERINSERT, TIMEINSERT) VALUES
      ('MARX', 'Very Good', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO MovieDetails (TITLE, DIRECTOR, YEAR_ESTABLISHED, DESC, USERINSERT, TIMEINSERT) VALUES
('KRATOS KAI EPANASTASH', 'LENIN',  '1917-09-25', 'Very Good', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO MovieDetails (TITLE, DIRECTOR, YEAR_ESTABLISHED, DESC, USERINSERT, TIMEINSERT) VALUES
('AREIANARA', 'PATSIMAS',  '1914-09-25', 'Very Good', 'EXADAKTYLOS', '2019-09-25');




