DROP TABLE IF EXISTS MOVIES;

INSERT INTO Movie (TITLE, DIRECTOR, YEAR_ESTABLISHED, DESC, USERINSERT, TIMEINSERT) VALUES
      ('OI ALHTES THS ZWHS', 'BOOTSROKE',  '2009-09-25', 'Very Good', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, DIRECTOR, YEAR_ESTABLISHED, DESC, USERINSERT, TIMEINSERT) VALUES
('HARRY POTTER', 'PATSIMAS',  '2000-09-25', 'Very Good', 'EXADAKTYLOS', '2019-09-25');
