DROP TABLE IF EXISTS MOVIES;

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
      ('OI ALHTES THS ZWHS', '2009-09-25', 'EXADAKTYLOS', '2019-09-25');

INSERT INTO Movie (TITLE, YEAR_ESTABLISHED, USERINSERT, TIMEINSERT) VALUES
('HARRY POTTER', '1917-09-25', 'EXADAKTYLOS', '2019-09-25');


--DROP TABLE IF EXISTS MOVIE_DETAILS;
--
--INSERT INTO MovieDetails (DIRECTOR, DESC, USERINSERT, TIMEINSERT, MOVIE_ID) VALUES
--      ('BOOTSROKE', 'Very Good', 'EXADAKTYLOS', '2019-09-25', 4);
--
--INSERT INTO MovieDetails (DIRECTOR, DESC, USERINSERT, TIMEINSERT, MOVIE_ID) VALUES
--('PATSIMAS', 'Very Good', 'EXADAKTYLOS', '2019-09-25', 5);





